### ISSUE TITLE
Я даже запустить не могу

### ISSUE THREAD

**Issue by D1midr0sh** [DuxaDruha/flower#1]
Почему так поздно? Дедлайн ведь уже через шесть часов))

**Comment by DuxaDruha** [comment]
В нас ещё 13 дней (Дмитрий Григорьевич сказал, что просто ссылку прислать,
а доделать можно до 13 мая)

вс, 30 апр. 2023 г., 17:26 Dmitriy Kirichenko ***@***.***>:

**Comment by D1midr0sh** [comment]
Позорище😁
